#!/bin/bash
#PBS -N XXNAMEXX
#PBS -P e14
#PBS -l ncpus=8
#PBS -l mem=8GB
#PBS -l walltime=04:00:00
#PBS -l wd
#PBS -l software=matlab_unsw
#PBS -l storage=gdata/hh5+gdata/ik11+scratch/e14+gdata/ua8+gdata/e14
#PBS -q express
#PBS -M ryan.holmes@unsw.edu.au
#PBS -m e

module load matlab
module load matlab_licence/unsw

#matlab -nodisplay -nodesktop -nosplash -r "output=XXOUTPUTXX;region='XXREGIONXX';Heat_Budget_Process_ProductionXXTYPEXX;exit;"
matlab -nodisplay -nodesktop -nosplash -r "output=XXOUTPUTXX;region='XXREGIONXX';Heat_Budget_Process_Variance;exit;"

